# Generated by Django 2.2.19 on 2022-12-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(error_messages={'unique': 'Такой ингредиент уже существует'}, help_text='Введите ингредиент', max_length=200, verbose_name='Ингредиент'),
        ),
    ]
