# Generated by Django 2.2.19 on 2022-12-19 20:08

from django.db import migrations

import colorfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221219_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Введите цвет тега в HEX', image_field=None, max_length=18, samples=None, verbose_name='Цвет тега HEX'),
        ),
    ]
