# Generated by Django 2.2.19 on 2022-12-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221220_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Введите ингредиент', max_length=200, verbose_name='Ингредиент'),
        ),
    ]
